@startuml trainer

' Include files
!include sampler.puml
!include metrics.puml
!include loss.puml
!include logger.puml
!include early_stop.puml
!include callbacks.puml

' === Clean modern look ===
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #2563EB
skinparam roundCorner 15
skinparam shadowing false

' Hide empty members
hide empty members

' Hide circle
hide circle

' Remove circles
skinparam CircledCharacterRadius 10

' Remove markers from parameters and methods
skinparam classAttributeIconSize 0

' ===== Diagram content =====
class Model {
    ** torch.nn.Module**
}

class Optimizer {
    ** torch.optim.Optimizer**
}

class ITrainer {
    **  abstract**
    --
    - ** model**: Module
    - ** sampler**: ISampler
    - ** loss**: ILoss
    - ** optimizer**: Optimizer
    - ** metrics**: Optional[IMetrics]
    - ** callbacks**: Optional[ICallbacks]
    - ** logger**: Optional[ILogger]
    - ** early_stop**: Optional[IEarlyStop]
    --
    + ** fit(**num_epochs: int, verbose: bool**)**: bool
}

' Relationships
IMetrics -up[#white]- IEarlyStop
IEarlyStop -up[#white]- ICallbacks
ICallbacks -up[#white]- ILogger

ITrainer <-up-  Model
ITrainer <-up-  Optimizer
ITrainer <-right-  ISampler
ITrainer <-down- ILoss

@enduml
