@startuml operator

' === Clean modern look ===
skinparam backgroundColor #FFFFFF
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #2563EB
skinparam roundCorner 15
skinparam shadowing false

' Hide empty members
hide empty members

' Hide circle
hide circle

' Remove circles
skinparam CircledCharacterRadius 10

' Remove markers from parameters and methods
skinparam classAttributeIconSize 0

' ===== Diagram content =====
class Operator {
    - **parameters**: Mapping
    - **operators**: Mapping
    ---
    + ** set_parameter(**name: str, axis: int, dim: int, io: str, loss: str, requires_grad: bool**)**: None
    + ** get_parameter(**name: str**)**: Tensor
    + ** predict(**model: Module, batch: Mapping[str, Tensor], source: str**)**: None
    + ...
}

class LossBase(ILoss) {
    + ** get_parameter(**name: str**)**: Tensor
    + ** get_operator(****)**: Operator
}

' Relationships
Operator ->  LossBase

@enduml
